on: [push]

jobs:
  ddns_update_job:
    runs-on: ubuntu-latest
    name: Doing test DDNS update on Unstoppable Domains Contracts
    steps:
      - name: Ddns update
        id: ddns-update
        uses: anantaramdas/unstoppable-domain-action@master
        with:
          mnemonic: ${{ secrets.ACTION_MNEMONIC }}
          rpc: ${{ secrets.ACTION_RPC }}
          name: aleksandrpopov.crypto
          contentHash: 'QmXHZXpTQMcXJxDUjV3YShVQoNcxoo6uaKEY2t2xJ3anxs'
          verbose: true
          dryrun: false